export const ACTION_NAME = {
  SIGNUP_USER: 'SIGNUP_USER',
  SIGNIN_USER: 'SIGNIN_USER',
  KEEP_AUTH_USER: 'KEEP_AUTH_USER',
  READ_PROJECTS: 'READ_PROJECTS',
  CREATE_PROJECT: 'CREATE_PROJECT',
  UPDATE_PROJECT: 'UPDATE_PROJECT',
  DELETE_PROJECT: 'DELETE_PROJECT',
  CREATE_LABEL: 'CREATE_LABEL',
  READ_LABELS: 'READ_LABELS',
  CREATE_TASK: 'CREATE_TASKS',
  READ_TASKS: 'READ_TASKS',
};
