export const ACTION_NAME = {
  SIGNUP_USER: 'SIGNUP_USER',
  SIGNIN_USER: 'SIGNIN_USER',
  KEEP_AUTH_USER: 'KEEP_AUTH_USER',
  READ_PROJECTS: 'READ_PROJECTS',
  CREATE_PROJECT: 'CREATE_PROJECT',
  UPDATE_PROJECT: 'UPDATE_PROJECT',
  DELETE_PROJECT: 'DELETE_PROJECT',
};
